version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "7895:7895"
    env_file:
      - .env
    environment:
      APP_ENV: production
      VITE_API_URL: ${BACKEND_URL}
    depends_on:
      - backend
    restart: unless-stopped

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "7893:7893"
    env_file:
      - .env
    environment:
      APP_ENV: production
      PORT: 7893
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5433/${POSTGRES_DB}
      REDIS_URL: redis://redis:6379
      FRONTEND_URL: ${FRONTEND_URL}
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  db:
    image: postgres:18
    ports:
      - "5433:5433"
    env_file:
      - .env
    environment:
      PGPORT: 5433
    volumes:
      - pgdata:/var/lib/postgresql-project-convergence/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p 5433",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379" # Only needed if you want to connect locally via tunnel
    restart: unless-stopped
    volumes:
      - redisdata:/data

volumes:
  pgdata:
  redisdata:
